'use strict';
const $ = id => document.getElementById(id);
// Grade bands are practice sets, not a claim of alignment to any school curriculum.
const vocabulary = [
 'A B C D E F G H I J K L M N O P Q R S T U V W X Y Z cat dog sun red blue egg bus cup pig hat pen',
 'apple banana orange grape lemon tiger lion monkey rabbit horse bird fish milk water bread cake chair table book pencil school happy sad green yellow black white',
 'family mother father sister brother teacher student kitchen bedroom garden window door breakfast dinner chicken hungry thirsty sleepy sunny rainy cloudy windy jacket shoes purple morning evening',
 'elephant giraffe butterfly dolphin mountain river forest island beach hospital library station restaurant supermarket bicycle airplane umbrella sandwich vegetable beautiful dangerous excited worried tomorrow yesterday',
 'adventure discover explore journey planet astronaut science experiment electricity energy recycle environment weather temperature season earthquake exercise healthy delicious favorite different important remember practice question answer',
 'responsibility imagination communication technology information transportation pollution protection conservation community volunteer opportunity confidence curious creative independent patient generous explain compare describe improve understand celebrate achieve'
].map(s => s.split(' '));
const descriptions = ['英文字母與簡單單字 · A、cat、sun','生活單字與動物 · apple、tiger','家庭、天氣與感受 · family、cloudy','場所與較長單字 · library、butterfly','自然科學與抽象詞 · energy、adventure','進階多音節單字 · responsibility'];
let grade = 0, mode = 'menu', bombs = [], effects = [], target = '', score = 0, hp = 100, elapsed = 0, cooldown = 0, wave = 1, nextSpawn = 0, nextPrompt = 0, roarUntil = 0, announcementUntil = 0, hits = 0, misses = 0, mistakes = 0, last = 0, serial = 0;
let width = 400, height = 800, audio, voices = [], speechToken = 0, speaking = false;
const canvas = $('scene'), ctx = canvas.getContext('2d'), reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
function resize(){const r=$('game').getBoundingClientRect();width=r.width;height=r.height;const d=Math.min(devicePixelRatio||1,2);canvas.width=width*d;canvas.height=height*d;ctx.setTransform(d,0,0,d,0,0);for(const b of bombs)b.x=Math.min(b.x,width-b.w-8);}
window.addEventListener('resize',()=>{resize();if(window.innerWidth>window.innerHeight&&window.innerHeight<600)pause();});resize();
function getVoices(){voices=window.speechSynthesis ? speechSynthesis.getVoices().filter(v=>/^en[-_]/i.test(v.lang)) : [];}
if(window.speechSynthesis){getVoices();speechSynthesis.addEventListener('voiceschanged',getVoices);}
else {$('audioNote').textContent='此瀏覽器不支援英文語音，請使用 Safari 或 Chrome。';$('start').disabled=true;}
function sound(type){if(!audio)return;try {const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);let t=audio.currentTime;o.type=type==='roar'?'sawtooth':'sine';o.frequency.setValueAtTime(type==='roar'?75:type==='hit'?680:120,t);o.frequency.exponentialRampToValueAtTime(type==='roar'?28:type==='hit'?1100:35,t+.3);g.gain.setValueAtTime(type==='roar'?.09:.045,t);g.gain.exponentialRampToValueAtTime(.001,t+(type==='roar'?.8:.3));o.start();o.stop(t+.85);}catch(e){/* Audio effects are optional; speech remains available. */}}
function cancelSpeech(){speechToken++;speaking=false;if(window.speechSynthesis)speechSynthesis.cancel();}
function speak(){if(mode!=='playing'||!target)return;cancelSpeech();const token=speechToken;const u=new SpeechSynthesisUtterance(target);u.lang='en-US';u.rate=.7+grade*.045;const v=voices.find(v=>v.lang==='en-US')||voices[0];if(v)u.voice=v;speaking=true;u.onend=()=>{if(token===speechToken)speaking=false;};u.onerror=e=>{if(token!==speechToken)return;speaking=false;if(e.error!=='canceled'&&e.error!=='interrupted'){pause();$('result').textContent='英文語音無法播放。請確認裝置已安裝英文語音，並開啟音量，再按繼續。';}};speechSynthesis.speak(u);nextPrompt=elapsed+Math.max(2.7,target.length*.12+1.7);}
function announce(text,seconds=1.6){$('announcement').textContent=text;announcementUntil=elapsed+seconds;}
function selectGrade(n){grade=n;[...$('grades').children].forEach((b,i)=>b.setAttribute('aria-pressed',String(i===n)));$('gradeInfo').textContent=descriptions[n];$('gradeLabel').textContent=`小${'一二三四五六'[n]} · 聽力防衛`;}
for(let i=0;i<6;i++){const b=document.createElement('button');b.textContent='小'+'一二三四五六'[i];b.onclick=()=>selectGrade(i);$('grades').append(b);}selectGrade(0);
function clearBombs(){for(const b of bombs)b.el.remove();bombs=[];}
function start(){cancelSpeech();clearBombs();effects=[];score=0;hp=100;elapsed=0;cooldown=0;wave=1;nextSpawn=1.2;nextPrompt=0;target='';hits=0;misses=0;mistakes=0;mode='playing';$('overlay').hidden=true;$('dialog').hidden=true;$('pause').disabled=false;$('listen').disabled=false;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();}catch(e){}roar();updateHUD();last=performance.now();const ready=new SpeechSynthesisUtterance('Ready');ready.lang='en-US';speechSynthesis.speak(ready);
 // Browsers that support orientation locking require fullscreen from a user gesture.
 if(window.innerWidth<700&&document.documentElement.requestFullscreen){document.documentElement.requestFullscreen().then(()=>{if(screen.orientation&&screen.orientation.lock)return screen.orientation.lock('portrait');}).catch(()=>{});}
}
function roar(){roarUntil=elapsed+1.1;sound('roar');announce(wave===1?'怪獸來了，準備聆聽！':'怪獸狂暴！密集轟炸',2);}
function spawn(){const pool=vocabulary[grade];const words=[];while(words.length<3){const word=pool[Math.floor(Math.random()*pool.length)];if(!words.includes(word))words.push(word);}const burst=wave>1;const count=burst?Math.min(12,5+wave):3;for(let i=0;i<count;i++){const word=words[i%3], w=Math.min(width-20,Math.max(72,word.length*9+22));const lane=i%3;const x=Math.min(width-w-8,Math.max(8,(width/3)*lane+(width/3-w)/2+(burst?(Math.random()-.5)*14:0)));const el=document.createElement('button');el.className='bomb';el.textContent=word;el.style.width=w+'px';el.style.fontSize=(word.length>12?14:word.length>8?16:20)+'px';el.setAttribute('aria-label','炸彈 '+word);const b={id:++serial,word,x,y:145-Math.floor(i/3)*58,w,el,speed:(height-340)/(14-grade*.75)*Math.min(1.9,1+(wave-1)*.1)};el.onclick=()=>hit(b);$('bombs').append(el);bombs.push(b);}pickTarget();}
function pickTarget(){const visible=bombs.filter(b=>b.y>=130);if(!visible.length){target='';return;}const choices=[...new Set(visible.map(b=>b.word))];const other=choices.filter(w=>w!==target);target=(other.length?other:choices)[Math.floor(Math.random()*(other.length||choices.length))];speak();}
function remove(b){b.el.remove();bombs=bombs.filter(x=>x!==b);}
function particle(x,y,color,label=''){effects.push({x,y,color,label,life:.65});}
function hit(b){if(mode!=='playing'||!bombs.includes(b))return;if(b.word!==target){score=Math.max(0,score-10);mistakes++;b.el.classList.remove('wrong');void b.el.offsetWidth;b.el.classList.add('wrong');$('hint').textContent='再仔細聽聽！點錯扣 10 分。';sound('miss');}else{score+=100;hits++;particle(b.x+b.w/2,b.y+20,'#9be6ce','+100');remove(b);sound('hit');$('hint').textContent='答對了！繼續聽下一個單字。';if(!bombs.some(x=>x.word===target))pickTarget();}updateHUD();}
function chain(){if(mode!=='playing'||cooldown>0||!target)return;const matches=bombs.filter(b=>b.word===target);if(!matches.length)return;let prev={x:width*.75,y:height-85};for(const b of matches){const point={x:b.x+b.w/2,y:b.y+24};effects.push({line:[prev,point],life:.6,color:'#aefbe0'});prev=point;score+=100;hits++;particle(point.x,point.y,'#aefbe0','+100');remove(b);}cooldown=18;sound('hit');announce(`閃電連鎖 × ${matches.length}`);pickTarget();updateHUD();}
function best(){try{return Number(localStorage.getItem('word-defense-best-'+grade))||0;}catch(e){return 0;}}
function end(){mode='over';cancelSpeech();const record=Math.max(best(),score);try{localStorage.setItem('word-defense-best-'+grade,record);}catch(e){}$('dialog').hidden=false;$('resultLabel').textContent='MISSION COMPLETE';$('dialogTitle').textContent='城市需要你再挑戰';$('result').textContent=`防衛積分 ${score}　｜　最高 ${record}\n守護 ${Math.floor(elapsed)} 秒 · 第 ${wave} 波\n答對 ${hits} 顆 · 漏接 ${misses} 顆 · 點錯 ${mistakes} 次`;$('resume').hidden=true;$('pause').disabled=true;updateHUD();}
function pause(){if(mode!=='playing')return;mode='paused';cancelSpeech();$('dialog').hidden=false;$('resultLabel').textContent='MISSION PAUSED';$('dialogTitle').textContent='休息一下';$('result').textContent='城市已暫停，準備好就繼續守護。';$('resume').hidden=false;updateHUD();}
function resume(){mode='playing';$('dialog').hidden=true;last=performance.now();speak();}
function updateHUD(){$('score').textContent=String(score).padStart(4,'0');$('wave').textContent='WAVE '+String(wave).padStart(2,'0');$('health').style.width=hp+'%';$('health').style.background=hp<30?'#ef8f7e':'#87d9ba';$('hp').textContent=hp+'%';$('skill').disabled=mode!=='playing'||cooldown>0||!target;$('listen').disabled=mode!=='playing'||!target;$('cooldown').textContent=cooldown>0?`冷卻 ${Math.ceil(cooldown)} 秒`:'準備就緒';}
$('start').onclick=start;$('restart').onclick=start;$('pause').onclick=pause;$('resume').onclick=resume;$('listen').onclick=speak;$('skill').onclick=chain;$('choose').onclick=()=>{mode='menu';cancelSpeech();clearBombs();effects=[];$('dialog').hidden=true;$('overlay').hidden=false;$('announcement').textContent='';$('pause').disabled=true;updateHUD();};document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});document.addEventListener('keydown',e=>{if(e.key==='Escape')pause();if(e.code==='Space'&&mode==='playing'){e.preventDefault();speak();}});
function draw(t){ctx.clearRect(0,0,width,height);const sky=ctx.createLinearGradient(0,0,0,height);sky.addColorStop(0,'#142639');sky.addColorStop(.7,'#345568');sky.addColorStop(1,'#193443');ctx.fillStyle=sky;ctx.fillRect(0,0,width,height);
 ctx.fillStyle='#c3d6ca';ctx.beginPath();ctx.arc(width*.79,height*.24,32,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff7';for(let i=0;i<35;i++){ctx.fillRect((i*79.7)%width,(i*47.3)%(height*.6),i%3===0?2:1,1);}
 // Original procedural kaiju silhouette: horns, shoulders, claws, and glowing eyes.
 ctx.save();ctx.translate(width*.49,height*.59);const scale=width/400;ctx.scale(scale,scale);if(elapsed<roarUntil&&!reduced)ctx.translate(Math.sin(t/35)*3,0);ctx.fillStyle='#102335';ctx.beginPath();ctx.moveTo(-170,160);ctx.lineTo(-158,12);ctx.lineTo(-126,-63);ctx.lineTo(-95,-75);ctx.lineTo(-88,-147);ctx.lineTo(-65,-121);ctx.lineTo(-40,-165);ctx.lineTo(-13,-151);ctx.lineTo(15,-168);ctx.lineTo(39,-140);ctx.lineTo(75,-168);ctx.lineTo(70,-103);ctx.lineTo(112,-69);ctx.lineTo(154,7);ctx.lineTo(178,160);ctx.closePath();ctx.fill();ctx.beginPath();ctx.ellipse(0,65,125,170,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=elapsed<roarUntil?'#ffbd78':'#86b9b1';ctx.shadowColor='#f7be76';ctx.shadowBlur=elapsed<roarUntil?24:8;ctx.beginPath();ctx.moveTo(-57,-97);ctx.lineTo(-15,-89);ctx.lineTo(-24,-81);ctx.lineTo(-51,-84);ctx.fill();ctx.beginPath();ctx.moveTo(14,-89);ctx.lineTo(56,-97);ctx.lineTo(50,-84);ctx.lineTo(23,-81);ctx.fill();ctx.shadowBlur=0;if(elapsed<roarUntil){ctx.fillStyle='#050d19';ctx.beginPath();ctx.ellipse(0,-51,24,22,0,0,Math.PI*2);ctx.fill();}ctx.restore();
 const ground=height-168;for(let layer=0;layer<2;layer++){for(let i=0;i<13;i++){const bw=width/11;const x=i*bw-15;const bh=(35+(i*31)%72)*(layer?1:.75);const damaged=layer&&hp<100-(i%5)*20;ctx.fillStyle=layer?'#152838':'#284756';ctx.fillRect(x,ground-bh+(damaged?bh*.3:0),bw-5,damaged?bh*.7:bh);if(layer){for(let row=0;row<4;row++)for(let col=0;col<2;col++){ctx.fillStyle=damaged?'#664d43':(i+row+col)%3?'#cfa876':'#47727e';ctx.fillRect(x+7+col*12,ground-12-row*15,4,6);}}}}
 ctx.fillStyle='#142b3a';ctx.fillRect(0,ground,width,7);for(const e of effects){ctx.globalAlpha=Math.max(0,e.life/.65);ctx.strokeStyle=e.color;ctx.fillStyle=e.color;if(e.line){ctx.lineWidth=3;ctx.shadowColor=e.color;ctx.shadowBlur=15;ctx.beginPath();ctx.moveTo(e.line[0].x,e.line[0].y);ctx.lineTo((e.line[0].x+e.line[1].x)/2+15,(e.line[0].y+e.line[1].y)/2);ctx.lineTo(e.line[1].x,e.line[1].y);ctx.stroke();ctx.shadowBlur=0;}else{ctx.lineWidth=3;ctx.beginPath();ctx.arc(e.x,e.y,(.7-e.life)*55,0,Math.PI*2);ctx.stroke();ctx.font='bold 20px sans-serif';ctx.textAlign='center';ctx.fillText(e.label,e.x,e.y-(.65-e.life)*40);}}ctx.globalAlpha=1;
}
function frame(t){const dt=Math.min(.05,(t-last)/1000||0);last=t;if(mode==='playing'){elapsed+=dt;cooldown=Math.max(0,cooldown-dt);const newWave=1+Math.floor(elapsed/30);if(newWave>wave){wave=newWave;roar();nextSpawn=elapsed+1.2;}if(elapsed>=nextSpawn&&bombs.length<18){spawn();nextSpawn=elapsed+Math.max(8,14-wave*.6);}if(target&&!speaking&&elapsed>=nextPrompt)pickTarget();if(!target&&bombs.some(b=>b.y>=130))pickTarget();for(const b of [...bombs]){b.y+=b.speed*dt;b.el.style.transform=`translate(${b.x}px,${b.y}px)`;b.el.style.visibility=b.y<125?'hidden':'visible';if(b.y>=height-213){remove(b);hp=Math.max(0,hp-5);misses++;particle(b.x+b.w/2,height-182,'#ffb27e','−5');sound('miss');if(hp===0){end();break;}}}if(target&&!bombs.some(b=>b.word===target))pickTarget();if(elapsed>announcementUntil)$('announcement').textContent='';effects.forEach(e=>e.life-=dt);effects=effects.filter(e=>e.life>0);updateHUD();}draw(t);requestAnimationFrame(frame);}requestAnimationFrame(frame);
